### ISSUE TITLE
为何不支持<!--more-->?

### ISSUE THREAD

**Issue by luckypoem** [StefanoChiodino/go-web#1]
hi.

as per ur repo,i setup a blog: http://scd.smt.biz.st , the post http://scd.smt.biz.st/post/2017/04/chinese-economy/ has no excerpt.why?

**Comment by StefanoChiodino** [comment]
Hi @luckypoem,

First of all your posts looks like have been written by me, could you please change that? There is my name in the header and at the bottom of the page.

I'm assuming that you are lamenting the fact that the blog post appears on your homepage in full. You are not using the same theme that I'm using, so you must have changed something, or be using a very old commit when I tried that theme. So I'm afraid I can't help you with that. It's possible that that theme outputs the posts in full.
